# Why use NUMPY?

In [1]:
import numpy as np

In [2]:
print("hello word")

hello word


In [3]:
import sklearn

In [4]:
i = 45

In [5]:
print(7)

7


In [6]:
myarr = np.array([[3, 6, 32, 7]], np.int64)

In [7]:
print(myarr)

[[ 3  6 32  7]]


In [8]:
myarr[0, 1]

6

In [9]:
myarr.shape

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0, 1] = 45

In [12]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

# Array creation: Conversion from other Python structures 

In [13]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [19]:
a1D = np.array([1, 2, 3, 4])

In [20]:
a1D

array([1, 2, 3, 4])

In [21]:
a2D = np.array([[1, 2], [3, 4]])

In [22]:
a2D

array([[1, 2],
       [3, 4]])

In [23]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [24]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [25]:
zeros = np.zeros((2, 5))

In [26]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
zeros.dtype

dtype('float64')

In [28]:
zeros.shape

(2, 5)

In [29]:
rng = np.arange(15)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# numpy.linspace

In [31]:
lspace = np.linspace(1,5,12)

In [32]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [33]:
emp = np.empty((4,6))

In [34]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23058707e-307, 8.45593934e-307, 7.56593017e-307],
       [1.11258854e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307, 6.23059726e-307, 9.34604358e-307],
       [6.23058028e-307, 1.24611266e-306, 1.37961030e-306,
        1.29061753e-306, 9.34601642e-307, 1.60219035e-306],
       [1.42418172e-306, 8.06610070e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306, 2.46151512e-312]])

In [35]:
empty_like = np.empty_like(lspace)

In [36]:
empty_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [37]:
ide = np.identity(45)

In [38]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
ide.shape

(45, 45)

In [40]:
arr = np.arange(99)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# NUMPY AXIS

In [44]:
x = [[1,2,3] , [4,5,6], [7,8,9]]

In [45]:
ar = np.array(x)

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
ar.sum(axis=0)   # all columns add

array([12, 15, 18])

In [48]:
ar.sum(axis=1)   # all rows are add

array([ 6, 15, 24])

In [49]:
ar.T  # array ko transpose kar dega

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
ar.flat

In [51]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [52]:
ar.size

9

In [53]:
ar.nbytes

36

In [54]:
one = np.array([1,3,4,634,2])

In [55]:
one.argmax()  #index deta hai kha maximum number hai

3

In [56]:
one.argmin()

0

# argsort

In [57]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar.argmin()

0

In [60]:
ar.argmax()

8

In [61]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [62]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [63]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [64]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [65]:
ar.ravel()  #straight in matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshaping arrays

In [66]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [70]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [71]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [74]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [75]:
np.sqrt(ar)   #squrt root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [76]:
ar.sum()

45

In [77]:
ar.max()

9

In [78]:
ar.min()

1

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [82]:
np.count_nonzero(ar)

9

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))